export const CATEGORIES = [
  'All',
  'Devotional Combo Packs',
  'Wall Decor & Key Holders',
  'Luxury Gift Hampers',
];

export const PRODUCTS = [
  {
    id: 'dcp-01',
    name: 'Royal Velvet Shringar Set (Size 3-5)',
    category: 'Devotional Combo Packs',
    price: 2499,
    originalPrice: 3299,
    rating: 4.8,
    reviews: 132,
    icon: 'Crown',
    badge: 'Bestseller',
    inStock: true,
  },
  {
    id: 'dcp-02',
    name: 'Gold-Zari Silk Poshak Combo',
    category: 'Devotional Combo Packs',
    price: 1899,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 98,
    icon: 'Sparkles',
    badge: null,
    inStock: true,
  },
  {
    id: 'dcp-03',
    name: 'Festive Laddu Gopal Accessory Kit',
    category: 'Devotional Combo Packs',
    price: 1299,
    originalPrice: 1699,
    rating: 4.6,
    reviews: 76,
    icon: 'Gem',
    badge: 'Only 4 left',
    inStock: true,
  },
  {
    id: 'wdk-01',
    name: 'Mandala Carved Wooden Key Holder',
    category: 'Wall Decor & Key Holders',
    price: 899,
    originalPrice: 1199,
    rating: 4.5,
    reviews: 61,
    icon: 'KeyRound',
    badge: null,
    inStock: true,
  },
  {
    id: 'wdk-02',
    name: 'Royal Peacock Wall Organizer',
    category: 'Wall Decor & Key Holders',
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviews: 145,
    icon: 'Feather',
    badge: 'Bestseller',
    inStock: true,
  },
  {
    id: 'wdk-03',
    name: 'Handcrafted Om Wall Panel',
    category: 'Wall Decor & Key Holders',
    price: 1199,
    originalPrice: 1599,
    rating: 4.6,
    reviews: 54,
    icon: 'Sun',
    badge: null,
    inStock: true,
  },
  {
    id: 'lgh-01',
    name: 'Diwali Radiance Gift Hamper',
    category: 'Luxury Gift Hampers',
    price: 2999,
    originalPrice: 3799,
    rating: 4.8,
    reviews: 89,
    icon: 'Gift',
    badge: 'Limited edition',
    inStock: true,
  },
  {
    id: 'lgh-02',
    name: 'Signature Festive Gift Box',
    category: 'Luxury Gift Hampers',
    price: 1999,
    originalPrice: 2599,
    rating: 4.7,
    reviews: 67,
    icon: 'PackageOpen',
    badge: null,
    inStock: true,
  },
  {
    id: 'lgh-03',
    name: 'Premium Puja Thali Hamper',
    category: 'Luxury Gift Hampers',
    price: 3499,
    originalPrice: 4299,
    rating: 4.9,
    reviews: 112,
    icon: 'Flame',
    badge: 'Bestseller',
    inStock: true,
  },
];
